### ISSUE TITLE
Mixin?

### ISSUE THREAD

**Issue by pke** [guyellis/react-log-lifecycle#1]
Wanted to create this myself, but as a mixin. Why did you choose to go with class extension?

**Comment by guyellis** [comment]
Basically because I've been creating class extensions and know how to do them. Haven't done a mixin yet. Would a mixin be better? How would you implement that? Could we have both?

**Comment by guyellis** [comment]
@pke Are you still interested in this as a mixin or okay to close this?

**Comment by pke** [comment]
No, thanks
