### ISSUE TITLE
Can this be made compatible with Node 6x?

### ISSUE THREAD

**Issue by aosalias** [guyellis/react-log-lifecycle#3]
Heyo - trying to get this to work with Node 6.

https://github.com/guyellis/react-log-lifecycle/pull/2

**Comment by guyellis** [comment]
Thanks for the PR @aosalias

**Comment by aosalias** [comment]
👍

**Comment by guyellis** [comment]
@aosalias I just published this to Npm as 1.1.0 if you want to consume if through Npm.
